tests: fix overlength buffer
The buffer was defined as 32 characters, but the string was 33
characters when including the NULL byte.

This led to build errors on Fedora:
/builddir/build/BUILD/mbedtls3.6-3.6.2-build/mbedtls-3.6.2/tests/src/psa_exercise_key.c:186:36: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
  186 |     unsigned char ciphertext[32] = "(wabblewebblewibblewobblewubble)";

Fix this by leaving out the size portion of the array definition becuase
C89 allows this.

Signed-off-by: Bill Roberts <bill.roberts@arm.com>